const products = [
  {
    id: 1,
    name: "Asgaard Sofa",
    price: 25000,
    image: "../Images/Asgaard sofa 1.png",
    reviews: 1200,
    stars: 4.2,
    description:
      "A luxurious and comfortable sofa designed for modern living rooms. Crafted with high-quality materials for long-lasting durability.",
    tags: ["sofa", "luxury", "living room", "modern"],
    category: "Furniture",
    serialNumber: "ASG-001",
  },
  {
    id: 2,
    name: "Bella Chair and Table",
    price: 15000,
    image: "../Images/Bella chair and table 1.png",
    reviews: 600,
    stars: 3.5,
    description:
      "Stylish chair and table set perfect for small spaces. Made with premium wood and cushioned seating for comfort.",
    tags: ["chair", "table", "modern", "space-saving"],
    category: "Furniture",
    serialNumber: "BEL-002",
  },
  {
    id: 3,
    name: "Cloud Sofa Three Seater + Ottoman",
    price: 55000,
    image: "../Images/Cloud sofa three seater + ottoman_3 1.png",
    reviews: 800,
    stars: 4.7,
    description:
      "A spacious three-seater sofa with a matching ottoman, designed for ultimate relaxation and comfort. Ideal for large living rooms.",
    tags: ["sofa", "ottoman", "comfortable", "spacious"],
    category: "Furniture",
    serialNumber: "CLO-003",
  },
  {
    id: 4,
    name: "Grain Coffee Table",
    price: 12000,
    image: "../Images/Grain coffee table 1.png",
    reviews: 1100,
    stars: 4.1,
    description:
      "A rustic coffee table with a natural wood finish. A perfect piece for adding warmth to your living space.",
    tags: ["coffee table", "rustic", "wooden", "living room"],
    category: "Furniture",
    serialNumber: "GRA-004",
  },
  {
    id: 5,
    name: "Granite Dining Table with Chairs",
    price: 45000,
    image: "../Images/Granite dining table with dining chair 1.png",
    reviews: 500,
    stars: 4.3,
    description:
      "Elegant dining table set with a granite top and matching chairs. Ideal for modern dining rooms and family gatherings.",
    tags: ["dining table", "granite", "chairs", "modern"],
    category: "Furniture",
    serialNumber: "GRA-005",
  },
  {
    id: 6,
    name: "Granite Square Side Table",
    price: 8000,
    image: "../Images/Granite square side table 1.png",
    reviews: 4800,
    stars: 4.6,
    description:
      "A sleek and stylish square side table made with high-quality granite, perfect for modern interiors.",
    tags: ["side table", "granite", "modern", "compact"],
    category: "Furniture",
    serialNumber: "GRA-006",
  },
  {
    id: 7,
    name: "Kent Coffee Table",
    price: 10000,
    image: "../Images/Kent coffee table 1.png",
    reviews: 150,
    stars: 3.9,
    description:
      "A minimalist coffee table with a clean design, perfect for contemporary spaces.",
    tags: ["coffee table", "minimalist", "modern", "living room"],
    category: "Furniture",
    serialNumber: "KEN-007",
  },
  {
    id: 8,
    name: "Maya Sofa Three Seater",
    price: 40000,
    image: "../Images/Maya sofa three seater 1.png",
    reviews: 200,
    stars: 4.0,
    description:
      "A stylish three-seater sofa with plush cushions, offering a perfect blend of comfort and design.",
    tags: ["sofa", "comfortable", "modern", "living room"],
    category: "Furniture",
    serialNumber: "MAY-008",
  },
  {
    id: 9,
    name: "Outdoor Bar Table and Stool",
    price: 20000,
    image: "../Images/Outdoor bar table and stool 1.png",
    reviews: 250,
    stars: 4.4,
    description:
      "Perfect for outdoor gatherings, this bar table set comes with matching stools and is designed to withstand the elements.",
    tags: ["bar table", "outdoor", "stools", "gatherings"],
    category: "Outdoor",
    serialNumber: "OUT-009",
  },
  {
    id: 10,
    name: "Outdoor Sofa Set",
    price: 35000,
    image: "../Images/Outdoor sofa set 1.png",
    reviews: 300,
    stars: 4.5,
    description:
      "A weather-resistant sofa set perfect for patios and outdoor lounges, offering comfort and style.",
    tags: ["sofa set", "outdoor", "patio", "comfortable"],
    category: "Outdoor",
    serialNumber: "OUT-010",
  },
  {
    id: 11,
    name: "Plain Console with Teak Mirror",
    price: 18000,
    image: "../Images/Plain console with teak mirror 1.png",
    reviews: 180,
    stars: 3.8,
    description:
      "A minimalist console table with a teak mirror, adding an elegant touch to your entryway or living room.",
    tags: ["console", "teak", "mirror", "minimalist"],
    category: "Furniture",
    serialNumber: "PLA-011",
  },
  {
    id: 12,
    name: "Reclaimed Teak Coffee Table",
    price: 15000,
    image: "../Images/Reclaimed teak coffee table 1.png",
    reviews: 400,
    stars: 4.2,
    description:
      "A sustainable coffee table made from reclaimed teak wood, offering rustic charm and eco-friendly appeal.",
    tags: ["coffee table", "reclaimed wood", "sustainable", "rustic"],
    category: "Furniture",
    serialNumber: "REC-012",
  },
  {
    id: 13,
    name: "Reclaimed Teak Sideboard",
    price: 30000,
    image: "../Images/Reclaimed teak Sideboard 1.png",
    reviews: 450,
    stars: 4.3,
    description:
      "A vintage sideboard crafted from reclaimed teak wood, perfect for storage and enhancing the aesthetic of your home.",
    tags: ["sideboard", "reclaimed wood", "vintage", "storage"],
    category: "Furniture",
    serialNumber: "REC-013",
  },
  {
    id: 14,
    name: "Rocket Single Seater",
    price: 12000,
    image: "../Images/Rocket single seater 1.png",
    reviews: 350,
    stars: 4.1,
    description:
      "A modern single seater chair with a sleek design, perfect for adding a touch of elegance to any room.",
    tags: ["single seater", "modern", "comfortable", "chair"],
    category: "Furniture",
    serialNumber: "ROC-014",
  },
  {
    id: 15,
    name: "Round Coffee Table Color 2",
    price: 14000,
    image: "../Images/Round coffee table_color 2 1.png",
    reviews: 280,
    stars: 4.0,
    description:
      "A stylish round coffee table that adds a contemporary vibe to your living room with its sleek design and color.",
    tags: ["coffee table", "round", "modern", "living room"],
    category: "Furniture",
    serialNumber: "ROU-015",
  },
  {
    id: 16,
    name: "SJP 0825",
    price: 10000,
    image: "../Images/SJP_0825.png",
    reviews: 220,
    stars: 3.7,
    description:
      "A compact and stylish coffee table with a contemporary design. Ideal for small living rooms or offices.",
    tags: ["coffee table", "compact", "stylish", "office"],
    category: "Furniture",
    serialNumber: "SJP-016",
  },
  {
    id: 17,
    name: "Trenton Modular Sofa 3",
    price: 48000,
    image: "../Images/Trenton modular sofa_3 1.png",
    reviews: 600,
    stars: 4.5,
    description:
      "A modular sofa set that allows you to customize the seating arrangement for ultimate comfort and style.",
    tags: ["sofa", "modular", "customizable", "living room"],
    category: "Furniture",
    serialNumber: "TRE-017",
  },
];

export default products;
